### ISSUE TITLE
Add Prometheus mode

### ISSUE THREAD

**Issue by StevenLeRoux** [ovh/noderig#21]
Prometheus mode would have two consequences : 

- Export metrics to prometheus format instead of sensision (avoid geo //)
- Replace dots in Metric Names with _ (dots are forbidden inside prometheus)

**Comment by d33d33** [comment]
Why do you want Prometheus format?

**Comment by StevenLeRoux** [comment]
Prometheus has become a defacto standard as an exposition format and is becoming OpenMetrics 1.0 format. It would make Noderig useful for the Prometheus ecosystem, not only for Beamium integration.
