### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by furious-helpdesk** [ovh/noderig#33]
Why it doesn't work for Windows ?

**Comment by FlorentinDUBOIS** [comment]
Some logs will be warmly welcome.

**Comment by LostInBrittany** [comment]
Hmmm, it simply says *not implemented yet* when trying to run it on Windows ;)

**Comment by FlorentinDUBOIS** [comment]
&#x1b;[34mINFO&#x1b;[0m[0003] Noderig starting
&#x1b;[34mINFO&#x1b;[0m[0003] Noderig started - 5
&#x1b;[34mINFO&#x1b;[0m[0003] Http started
&#x1b;[34mINFO&#x1b;[0m[0003] Started
&#x1b;[34mINFO&#x1b;[0m[0003] Listen 127.0.0.1:9100
panic: runtime error: integer divide by zero

goroutine 20 [running]:
github.com/ovh/noderig/vendor/github.com/shirou/gopsutil/mem.SwapMemoryWithContext(0x850380, 0x1fd9e0dc, 0x1feda000, 0x0, 0x0)
        /home/eric/go/src/github.com/ovh/noderig/vendor/github.com/shirou/gopsutil/mem/mem_windows.go:87 +0x171
github.com/ovh/noderig/vendor/github.com/shirou/gopsutil/mem.SwapMemory(0x1feda000, 0x0, 0x0)
        /home/eric/go/src/github.com/ovh/noderig/vendor/github.com/shirou/gopsutil/mem/mem_windows.go:70 +0x2d
github.com/ovh/noderig/collectors.(*Memory).scrape(0x1fe821c0, 0x0, 0x0)
        /home/eric/go/src/github.com/ovh/noderig/collectors/memory.go:58 +0x57
github.com/ovh/noderig/collectors.NewMemory.func1(0x1fe8a140, 0x1fe821c0)
        /home/eric/go/src/github.com/ovh/noderig/collectors/memory.go:33 +0x58
created by github.com/ovh/noderig/collectors.NewMemory
        /home/eric/go/src/github.com/ovh/noderig/collectors/memory.go:31 +0x74

**Comment by FlorentinDUBOIS** [comment]
Windows is not supported yet
