### ISSUE TITLE
Custom port in the config

### ISSUE THREAD

**Issue by GTB3NW** [ovh/noderig#72]
Hi, the port 9100 conflicts with node-metrics and stops deployment of it for many situations if noderig isn't removed. As a temporary measure I've removed noderig from my servers, but ideally I'd like to configure it within the noderig config file (without patching service scripts) so I can continue shipping off metrics to the RTM dashboard. Alternatively is there a way to configure RTM's to be compatible with node-metrics?

Kind Regards,

Ben

**Comment by aurrelhebert** [comment]
Hello @GTB3NW, you can already start noderig with a different port. Noderig support a `listen` flag:

```sh
./noderig --listen 127.0.0.1:9101
```
The listen properies can also be set directly in Noderig config. It will overwrite the default port set to 9100.
```yaml
listen: 127.0.0.1:9101
```
